// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for DeleteNodeParamsForce.
const (
	DeleteNodeParamsForceTrue DeleteNodeParamsForce = "true"
)

// Defines values for GetSubscriptionParamsFormat.
const (
	Singbox GetSubscriptionParamsFormat = "singbox"
	V2ray   GetSubscriptionParamsFormat = "v2ray"
)

// Defines values for ListSyncJobsParamsStatus.
const (
	Failed  ListSyncJobsParamsStatus = "failed"
	Queued  ListSyncJobsParamsStatus = "queued"
	Running ListSyncJobsParamsStatus = "running"
	Success ListSyncJobsParamsStatus = "success"
)

// Defines values for GetTrafficTimeseriesParamsBucket.
const (
	Day    GetTrafficTimeseriesParamsBucket = "day"
	Hour   GetTrafficTimeseriesParamsBucket = "hour"
	Minute GetTrafficTimeseriesParamsBucket = "minute"
)

// Defines values for ListUsersParamsStatus.
const (
	Active          ListUsersParamsStatus = "active"
	Disabled        ListUsersParamsStatus = "disabled"
	Expired         ListUsersParamsStatus = "expired"
	TrafficExceeded ListUsersParamsStatus = "traffic_exceeded"
)

// Defines values for DeleteUserParamsHard.
const (
	DeleteUserParamsHardTrue DeleteUserParamsHard = "true"
)

// AdminProfile defines model for AdminProfile.
type AdminProfile struct {
	Username string `json:"username"`
}

// BootstrapRequest defines model for BootstrapRequest.
type BootstrapRequest struct {
	ConfirmPassword string  `json:"confirm_password"`
	Password        string  `json:"password"`
	SetupToken      *string `json:"setup_token,omitempty"`
	Username        string  `json:"username"`
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	Ok bool `json:"ok"`
}

// BootstrapStatus defines model for BootstrapStatus.
type BootstrapStatus struct {
	NeedsSetup bool `json:"needs_setup"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateInboundRequest defines model for CreateInboundRequest.
type CreateInboundRequest struct {
	ListenPort        int                     `json:"listen_port"`
	NodeId            int64                   `json:"node_id"`
	Protocol          string                  `json:"protocol"`
	PublicPort        *int                    `json:"public_port,omitempty"`
	Settings          map[string]interface{}  `json:"settings"`
	Tag               string                  `json:"tag"`
	TlsSettings       *map[string]interface{} `json:"tls_settings,omitempty"`
	TransportSettings *map[string]interface{} `json:"transport_settings,omitempty"`
}

// CreateNodeRequest defines model for CreateNodeRequest.
type CreateNodeRequest struct {
	ApiAddress    string `json:"api_address"`
	ApiPort       int    `json:"api_port"`
	GroupId       *int64 `json:"group_id"`
	Name          string `json:"name"`
	PublicAddress string `json:"public_address"`
	SecretKey     string `json:"secret_key"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Username string `json:"username"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Group defines model for Group.
type Group struct {
	Description string `json:"description"`
	Id          int64  `json:"id"`
	MemberCount int64  `json:"member_count"`
	Name        string `json:"name"`
}

// GroupUsersListItem defines model for GroupUsersListItem.
type GroupUsersListItem struct {
	Id           int64  `json:"id"`
	Status       string `json:"status"`
	TrafficLimit int64  `json:"traffic_limit"`
	TrafficUsed  int64  `json:"traffic_used"`
	Username     string `json:"username"`
	Uuid         string `json:"uuid"`
}

// GroupUsersReplaceRequest defines model for GroupUsersReplaceRequest.
type GroupUsersReplaceRequest struct {
	UserIds []int64 `json:"user_ids"`
}

// Inbound defines model for Inbound.
type Inbound struct {
	Id                int64                  `json:"id"`
	ListenPort        int                    `json:"listen_port"`
	NodeId            int64                  `json:"node_id"`
	Protocol          string                 `json:"protocol"`
	PublicPort        int                    `json:"public_port"`
	Settings          map[string]interface{} `json:"settings"`
	Tag               string                 `json:"tag"`
	TlsSettings       map[string]interface{} `json:"tls_settings"`
	TransportSettings map[string]interface{} `json:"transport_settings"`
	Uuid              string                 `json:"uuid"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	ExpiresAt string `json:"expires_at"`
	Token     string `json:"token"`
}

// Node defines model for Node.
type Node struct {
	ApiAddress    string     `json:"api_address"`
	ApiPort       int        `json:"api_port"`
	GroupId       *int64     `json:"group_id"`
	Id            int64      `json:"id"`
	LastSeenAt    *time.Time `json:"last_seen_at"`
	Name          string     `json:"name"`
	PublicAddress string     `json:"public_address"`
	SecretKey     string     `json:"secret_key"`
	Status        string     `json:"status"`
	Uuid          string     `json:"uuid"`
}

// NodeTrafficSample defines model for NodeTrafficSample.
type NodeTrafficSample struct {
	Download   int64   `json:"download"`
	Id         int64   `json:"id"`
	InboundTag *string `json:"inbound_tag"`
	RecordedAt string  `json:"recorded_at"`
	Upload     int64   `json:"upload"`
}

// SingBoxConfigRequest defines model for SingBoxConfigRequest.
type SingBoxConfigRequest struct {
	Config string  `json:"config"`
	Mode   *string `json:"mode,omitempty"`
}

// SingBoxGenerateRequest defines model for SingBoxGenerateRequest.
type SingBoxGenerateRequest struct {
	Command string `json:"command"`
}

// StatusOk defines model for StatusOk.
type StatusOk struct {
	Status string `json:"status"`
}

// SyncAttempt defines model for SyncAttempt.
type SyncAttempt struct {
	AttemptNo    int        `json:"attempt_no"`
	BackoffMs    int64      `json:"backoff_ms"`
	DurationMs   int64      `json:"duration_ms"`
	ErrorSummary string     `json:"error_summary"`
	FinishedAt   *time.Time `json:"finished_at"`
	HttpStatus   int        `json:"http_status"`
	Id           int64      `json:"id"`
	StartedAt    time.Time  `json:"started_at"`
	Status       string     `json:"status"`
}

// SyncJobDetail defines model for SyncJobDetail.
type SyncJobDetail struct {
	Attempts []SyncAttempt   `json:"attempts"`
	Job      SyncJobListItem `json:"job"`
}

// SyncJobListItem defines model for SyncJobListItem.
type SyncJobListItem struct {
	ActiveUserCount int        `json:"active_user_count"`
	AttemptCount    int        `json:"attempt_count"`
	CreatedAt       time.Time  `json:"created_at"`
	DurationMs      int64      `json:"duration_ms"`
	ErrorSummary    string     `json:"error_summary"`
	FinishedAt      *time.Time `json:"finished_at"`
	Id              int64      `json:"id"`
	InboundCount    int        `json:"inbound_count"`
	NodeId          int64      `json:"node_id"`
	ParentJobId     *int64     `json:"parent_job_id"`
	PayloadHash     string     `json:"payload_hash"`
	StartedAt       *time.Time `json:"started_at"`
	Status          string     `json:"status"`
	TriggerSource   string     `json:"trigger_source"`
}

// SyncResult defines model for SyncResult.
type SyncResult struct {
	Error  *string `json:"error,omitempty"`
	Status string  `json:"status"`
}

// SystemInfo defines model for SystemInfo.
type SystemInfo struct {
	PanelCommitId  string `json:"panel_commit_id"`
	PanelVersion   string `json:"panel_version"`
	SingBoxVersion string `json:"sing_box_version"`
}

// SystemSettings defines model for SystemSettings.
type SystemSettings struct {
	SubscriptionBaseUrl string `json:"subscription_base_url"`
	Timezone            string `json:"timezone"`
}

// TrafficNodeSummary defines model for TrafficNodeSummary.
type TrafficNodeSummary struct {
	Download       int64  `json:"download"`
	Inbounds       int64  `json:"inbounds"`
	LastRecordedAt string `json:"last_recorded_at"`
	NodeId         int64  `json:"node_id"`
	Samples        int64  `json:"samples"`
	Upload         int64  `json:"upload"`
}

// TrafficTimeseriesPoint defines model for TrafficTimeseriesPoint.
type TrafficTimeseriesPoint struct {
	BucketStart string `json:"bucket_start"`
	Download    int64  `json:"download"`
	Upload      int64  `json:"upload"`
}

// TrafficTotalSummary defines model for TrafficTotalSummary.
type TrafficTotalSummary struct {
	Download       int64  `json:"download"`
	Inbounds       int64  `json:"inbounds"`
	LastRecordedAt string `json:"last_recorded_at"`
	Nodes          int64  `json:"nodes"`
	Samples        int64  `json:"samples"`
	Upload         int64  `json:"upload"`
}

// UpdateAdminProfileRequest defines model for UpdateAdminProfileRequest.
type UpdateAdminProfileRequest struct {
	ConfirmPassword *string `json:"confirm_password,omitempty"`
	NewPassword     *string `json:"new_password,omitempty"`
	NewUsername     *string `json:"new_username,omitempty"`
	OldPassword     string  `json:"old_password"`
}

// UpdateGroupRequest defines model for UpdateGroupRequest.
type UpdateGroupRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UpdateInboundRequest defines model for UpdateInboundRequest.
type UpdateInboundRequest struct {
	ListenPort        *int                    `json:"listen_port,omitempty"`
	Protocol          *string                 `json:"protocol,omitempty"`
	PublicPort        *int                    `json:"public_port,omitempty"`
	Settings          *map[string]interface{} `json:"settings,omitempty"`
	Tag               *string                 `json:"tag,omitempty"`
	TlsSettings       *map[string]interface{} `json:"tls_settings,omitempty"`
	TransportSettings *map[string]interface{} `json:"transport_settings,omitempty"`
}

// UpdateNodeRequest defines model for UpdateNodeRequest.
type UpdateNodeRequest struct {
	ApiAddress    *string `json:"api_address,omitempty"`
	ApiPort       *int    `json:"api_port,omitempty"`
	GroupId       *int64  `json:"group_id"`
	Name          *string `json:"name,omitempty"`
	PublicAddress *string `json:"public_address,omitempty"`
	SecretKey     *string `json:"secret_key,omitempty"`
}

// UpdateSystemSettingsRequest defines model for UpdateSystemSettingsRequest.
type UpdateSystemSettingsRequest struct {
	SubscriptionBaseUrl *string `json:"subscription_base_url,omitempty"`
	Timezone            *string `json:"timezone,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	ExpireAt        *string `json:"expire_at,omitempty"`
	Status          *string `json:"status,omitempty"`
	TrafficLimit    *int64  `json:"traffic_limit,omitempty"`
	TrafficResetDay *int    `json:"traffic_reset_day,omitempty"`
	Username        *string `json:"username,omitempty"`
}

// User defines model for User.
type User struct {
	ExpireAt        *time.Time `json:"expire_at"`
	GroupIds        []int64    `json:"group_ids"`
	Id              int64      `json:"id"`
	Status          string     `json:"status"`
	TrafficLimit    int64      `json:"traffic_limit"`
	TrafficResetDay int        `json:"traffic_reset_day"`
	TrafficUsed     int64      `json:"traffic_used"`
	Username        string     `json:"username"`
	Uuid            string     `json:"uuid"`
}

// UserGroupsRequest defines model for UserGroupsRequest.
type UserGroupsRequest struct {
	GroupIds []int64 `json:"group_ids"`
}

// IdPath defines model for IdPath.
type IdPath = int64

// LimitParam defines model for LimitParam.
type LimitParam = int

// OffsetParam defines model for OffsetParam.
type OffsetParam = int

// BadGateway defines model for BadGateway.
type BadGateway = Error

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// BootstrapParams defines parameters for Bootstrap.
type BootstrapParams struct {
	XSetupToken *string `json:"X-Setup-Token,omitempty"`
}

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListInboundsParams defines parameters for ListInbounds.
type ListInboundsParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
	NodeId *int64       `form:"node_id,omitempty" json:"node_id,omitempty"`
}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// DeleteNodeParams defines parameters for DeleteNode.
type DeleteNodeParams struct {
	// Force Force delete with inbound drain
	Force *DeleteNodeParamsForce `form:"force,omitempty" json:"force,omitempty"`
}

// DeleteNodeParamsForce defines parameters for DeleteNode.
type DeleteNodeParamsForce string

// ListNodeTrafficParams defines parameters for ListNodeTraffic.
type ListNodeTrafficParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetSubscriptionParams defines parameters for GetSubscription.
type GetSubscriptionParams struct {
	Format *GetSubscriptionParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetSubscriptionParamsFormat defines parameters for GetSubscription.
type GetSubscriptionParamsFormat string

// ListSyncJobsParams defines parameters for ListSyncJobs.
type ListSyncJobsParams struct {
	Limit         *LimitParam               `form:"limit,omitempty" json:"limit,omitempty"`
	Offset        *OffsetParam              `form:"offset,omitempty" json:"offset,omitempty"`
	NodeId        *int64                    `form:"node_id,omitempty" json:"node_id,omitempty"`
	Status        *ListSyncJobsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	TriggerSource *string                   `form:"trigger_source,omitempty" json:"trigger_source,omitempty"`
	From          *time.Time                `form:"from,omitempty" json:"from,omitempty"`
	To            *time.Time                `form:"to,omitempty" json:"to,omitempty"`
}

// ListSyncJobsParamsStatus defines parameters for ListSyncJobs.
type ListSyncJobsParamsStatus string

// GetTrafficNodesSummaryParams defines parameters for GetTrafficNodesSummary.
type GetTrafficNodesSummaryParams struct {
	// Window Time window (e.g. 24h, 7d, 30d, all)
	Window *string `form:"window,omitempty" json:"window,omitempty"`
}

// GetTrafficTimeseriesParams defines parameters for GetTrafficTimeseries.
type GetTrafficTimeseriesParams struct {
	// Window Time window (e.g. 24h, 7d, 30d, all)
	Window *string `form:"window,omitempty" json:"window,omitempty"`

	// Bucket Time bucket granularity
	Bucket *GetTrafficTimeseriesParamsBucket `form:"bucket,omitempty" json:"bucket,omitempty"`
	NodeId *int64                            `form:"node_id,omitempty" json:"node_id,omitempty"`
}

// GetTrafficTimeseriesParamsBucket defines parameters for GetTrafficTimeseries.
type GetTrafficTimeseriesParamsBucket string

// GetTrafficTotalSummaryParams defines parameters for GetTrafficTotalSummary.
type GetTrafficTotalSummaryParams struct {
	// Window Time window (e.g. 24h, 7d, 30d, all)
	Window *string `form:"window,omitempty" json:"window,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Limit  *LimitParam            `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetParam           `form:"offset,omitempty" json:"offset,omitempty"`
	Status *ListUsersParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListUsersParamsStatus defines parameters for ListUsers.
type ListUsersParamsStatus string

// DeleteUserParams defines parameters for DeleteUser.
type DeleteUserParams struct {
	// Hard Hard delete (permanent removal)
	Hard *DeleteUserParamsHard `form:"hard,omitempty" json:"hard,omitempty"`
}

// DeleteUserParamsHard defines parameters for DeleteUser.
type DeleteUserParamsHard string

// BootstrapJSONRequestBody defines body for Bootstrap for application/json ContentType.
type BootstrapJSONRequestBody = BootstrapRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// UpdateAdminProfileJSONRequestBody defines body for UpdateAdminProfile for application/json ContentType.
type UpdateAdminProfileJSONRequestBody = UpdateAdminProfileRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = UpdateGroupRequest

// ReplaceGroupUsersJSONRequestBody defines body for ReplaceGroupUsers for application/json ContentType.
type ReplaceGroupUsersJSONRequestBody = GroupUsersReplaceRequest

// CreateInboundJSONRequestBody defines body for CreateInbound for application/json ContentType.
type CreateInboundJSONRequestBody = CreateInboundRequest

// UpdateInboundJSONRequestBody defines body for UpdateInbound for application/json ContentType.
type UpdateInboundJSONRequestBody = UpdateInboundRequest

// CreateNodeJSONRequestBody defines body for CreateNode for application/json ContentType.
type CreateNodeJSONRequestBody = CreateNodeRequest

// UpdateNodeJSONRequestBody defines body for UpdateNode for application/json ContentType.
type UpdateNodeJSONRequestBody = UpdateNodeRequest

// CheckSingBoxJSONRequestBody defines body for CheckSingBox for application/json ContentType.
type CheckSingBoxJSONRequestBody = SingBoxConfigRequest

// FormatSingBoxJSONRequestBody defines body for FormatSingBox for application/json ContentType.
type FormatSingBoxJSONRequestBody = SingBoxConfigRequest

// GenerateSingBoxJSONRequestBody defines body for GenerateSingBox for application/json ContentType.
type GenerateSingBoxJSONRequestBody = SingBoxGenerateRequest

// UpdateSystemSettingsJSONRequestBody defines body for UpdateSystemSettings for application/json ContentType.
type UpdateSystemSettingsJSONRequestBody = UpdateSystemSettingsRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// ReplaceUserGroupsJSONRequestBody defines body for ReplaceUserGroups for application/json ContentType.
type ReplaceUserGroupsJSONRequestBody = UserGroupsRequest
