package api

import (
  "errors"

  "sboard/panel/internal/config"
  "sboard/panel/internal/db"
)

// Compile-time check that Server implements StrictServerInterface.
var _ StrictServerInterface = (*Server)(nil)

var errInvalidPagination = errors.New("invalid pagination")

// Server implements the StrictServerInterface generated by oapi-codegen.
type Server struct {
  store        *db.Store
  cfg          config.Config
  singBoxTools SingBoxTools
}

func NewServer(store *db.Store, cfg config.Config, singBoxTools SingBoxTools) *Server {
  return &Server{
    store:        store,
    cfg:          cfg,
    singBoxTools: singBoxTools,
  }
}

// storeReady returns false if the store is nil (e.g. during bootstrap-only mode).
func (s *Server) storeReady() bool {
  return s.store != nil
}

// paginationDefaults validates and returns (limit, offset) with defaults applied.
// Returns errInvalidPagination for out-of-range values.
func paginationDefaults(limit *LimitParam, offset *OffsetParam) (int, int, error) {
  l := defaultListLimit
  if limit != nil {
    l = *limit
    if l < 0 || l > maxListLimit {
      return 0, 0, errInvalidPagination
    }
  }
  o := 0
  if offset != nil {
    o = *offset
    if o < 0 {
      return 0, 0, errInvalidPagination
    }
  }
  return l, o, nil
}

// errBadRequest returns an Error value for use in 400 responses.
func errBadRequest(msg string) BadRequestJSONResponse {
	return BadRequestJSONResponse{Error: msg}
}

// errNotFound returns an Error value for use in 404 responses.
func errNotFound(msg string) NotFoundJSONResponse {
	return NotFoundJSONResponse{Error: msg}
}

// errConflict returns an Error value for use in 409 responses.
func errConflict(msg string) ConflictJSONResponse {
	return ConflictJSONResponse{Error: msg}
}

// errInternal returns an Error value for use in 500 responses.
func errInternal(msg string) InternalErrorJSONResponse {
	return InternalErrorJSONResponse{Error: msg}
}

// errUnauthorized returns an Error value for use in 401 responses.
func errUnauthorized(msg string) UnauthorizedJSONResponse {
	return UnauthorizedJSONResponse{Error: msg}
}

// errBadGateway returns an Error value for use in 502 responses.
func errBadGateway(msg string) BadGatewayJSONResponse {
	return BadGatewayJSONResponse{Error: msg}
}
